# OOP_Task
Сусло Глеб.

Прикрепил следующую часть. Ветка Exceptions.

Все верно. Задание принял
